server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tenure
    username: root
    password: 1030
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true